[package]
name = "solana_libra_execution_client"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
grpcio = { version = "0.4.4", default-features = false, features = ["protobuf-codec"] }

execution_proto = { path = "../execution_proto", package = "solana_libra_execution_proto" }
failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext" }
types = { path = "../../types", package = "solana_libra_types" }
proto_conv = { path = "../../common/proto_conv", package = "solana_libra_proto_conv" }
