[package]
name = "solana_libra_benchmark"
version = "0.0.0-sol5"
authors = ["Libra <oncall+libra@xmail.facebook.com>"]
publish = false
edition = "2018"

[dependencies]
bincode = "1.1.4"
clap = "2.33.0"
futures = "0.1.28"
grpcio = { version = "0.4", default-features = false, features = ["protobuf-codec"] }
itertools = "0.8.0"
lazy_static = "1.2.0"
protobuf = "2.7"
regex = "1.1.9"
structopt = "0.2.15"

admission_control_proto = { path = "../admission_control/admission_control_proto", package = "solana_libra_admission_control_proto", version = "0.0.0-sol5" }
client = { path = "../client", package = "solana_libra_client", version = "0.0.0-sol5" }
config = { path = "../config", package = "solana_libra_config", version = "0.0.0-sol5" }
crypto = { path = "../crypto/legacy_crypto", package = "solana_libra_crypto", version = "0.0.0-sol5" }
debug_interface = { path = "../common/debug_interface", package = "solana_libra_debug_interface", version = "0.0.0-sol5" }
failure = { path = "../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol5" }
generate_keypair = { path = "../config/generate_keypair", package = "solana_libra_generate_keypair", version = "0.0.0-sol5" }
libra_wallet = { path = "../client/libra_wallet", package = "solana_libra_wallet", version = "0.0.0-sol5" }
libra_swarm = { path = "../libra_swarm", package = "solana_libra_swarm", version = "0.0.0-sol5" }
logger = { path = "../common/logger", package = "solana_libra_logger", version = "0.0.0-sol5" }
metrics = { path = "../common/metrics", package = "solana_libra_metrics", version = "0.0.0-sol5" }
proto_conv = { path = "../common/proto_conv", package = "solana_libra_proto_conv", version = "0.0.0-sol5" }
rusty-fork = "0.2.1"
types = { path = "../types", package = "solana_libra_types", version = "0.0.0-sol5" }
vm_genesis = { path = "../language/vm/vm_genesis", package = "solana_libra_vm_genesis", version = "0.0.0-sol5" }
