[package]
name = "solana_libra_vm_runtime_types"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bit-vec = "0.6.1"
lazy_static = "1.3.0"
proptest = "0.9"
sha2 = "0.8.0"
solana-libra-types = { path = "../../../../types" }
solana-libra-vm = { path = "../../" }
solana_libra_canonical_serialization = { path = "../../../../common/canonical_serialization" }
solana-libra-crypto = { path = "../../../../crypto/crypto" }
failure = { path = "../../../../common/failure_ext", package = "solana_libra_failure_ext" }

[dev-dependencies]
solana-libra-types = { path = "../../../../types", features = ["testing"] }
solana-libra-vm = { path = "../../", features = ["testing"]}

[features]
instruction_synthesis = []
testing = ["solana-libra-types/testing"]
