[package]
name = "solana_libra_metrics"
version = "0.0.0-sol14"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra metrics"
license = "Apache-2.0"
edition = "2018"

[dependencies]
futures = "0.1.28"
grpcio = { version = "0.4.3", default-features = false, features = ["protobuf-codec"] }
hyper = "0.12.33"
lazy_static = "1.3.0"
protobuf = "=2.8.0"
serde_json = "1.0.40"

failure = { path = "../failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol14" }
logger = { path = "../logger", package = "solana_libra_logger", version = "0.0.0-sol14" }

[dependencies.prometheus]
version  = "0.4.2"
default-features = false
features = ["push"]

[dev-dependencies]
rusty-fork = "0.2.1"
assert_approx_eq = "1.1.0"
