[package]
name = "solana-libra-metrics"
version = "0.0.1-sol2"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra metrics"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
edition = "2018"

[dependencies]
futures = "0.1.28"
grpcio = { version = "=0.5.0-alpha.4", default-features = false, optional = true }
hyper = "0.12.34"
lazy_static = "1.3.0"
serde_json = "1.0.40"
prometheus = { version = "0.7.0", default-features = false }

failure = { path = "../failure_ext", version = "0.0.1-sol2", package = "solana_libra_failure_ext" }
solana-libra-logger = { path = "../logger", version = "0.0.1-sol2" }

[dev-dependencies]
rusty-fork = "0.2.1"
assert_approx_eq = "1.1.0"

[features]
service-metrics = ["grpcio"]
default = ["service-metrics"]