[package]
name = "solana-libra-cost-synthesis"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra cost-synthesis"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
csv = "1.1.1"
rand = "0.6.5"
lazy_static = "1.3.0"

solana_libra_bytecode_verifier = { path = "../../bytecode_verifier" }
solana-libra-stdlib = { path = "../../stdlib" }
solana-libra-types = { path = "../../../types" }
solana-libra-vm = { path = "../../vm" }
solana_libra_vm_runtime = { path = "../../vm/vm_runtime" }
solana_libra_vm_runtime_types = { path = "../../vm/vm_runtime/vm_runtime_types" }
solana_libra_language_e2e_tests = { path = "../../e2e_tests" }
solana_libra_vm_cache_map = { path = "../../vm/vm_runtime/vm_cache_map" }
solana-libra-crypto = { path = "../../../crypto/crypto" }
structopt = "0.3.2"

[dev-dependencies]
solana-libra-types = { path = "../../../types", features = ["testing"] }

[features]
default = ["solana_libra_vm_runtime/instruction_synthesis"]
