[package]
name = "solana_libra_bytecode_verifier_tests"
version = "0.0.1-sol2"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra bytecode verifier tests"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dev-dependencies]
petgraph = "0.4"
proptest = "0.9.2"
solana_libra_bytecode_verifier = {path = "../", version = "0.0.1-sol2", features = ["testing"]}
failure = { path = "../../../common/failure_ext", version = "0.0.1-sol2", package = "solana_libra_failure_ext" }
solana-libra-types = { path = "../../../types", version = "0.0.1-sol2", features = ["testing"]}
solana_libra_invalid_mutations = { path = "../invalid_mutations", version = "0.0.1-sol2" }
solana-libra-vm = { path = "../../vm", version = "0.0.1-sol2", features = ["testing"]}
