[package]
name = "solana-libra-cluster-test"
version = "0.0.1-sol2"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra cluster test"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }
grpcio = { version = "=0.5.0-alpha.4", default-features = false, features = ["prost-codec"] }
itertools = "0.8.0"
rand = "0.6.5"
regex = { version = "1.3.0", default-features = false, features = ["std", "perf"] }
reqwest = { version="0.9.19", features=["rustls-tls"], default_features = false }
rusoto_core = {version = "0.40.0", features=["rustls"], default_features = false}
rusoto_ec2 = {version = "0.40.0", features=["rustls"], default_features = false}
rusoto_ecr = {version = "0.40.0", features=["rustls"], default_features = false}
rusoto_ecs = {version = "0.40.0", features=["rustls"], default_features = false}
rusoto_kinesis = {version = "0.40.0", features=["rustls"], default_features = false}
rusoto_logs = {version = "0.40.0", features=["rustls"], default_features = false}
serde_json = "1.0"
termion = "1.5.3"
serde = { version = "1.0.89", features = ["derive"] }
structopt = "0.3.2"

slog = { version = "2.5.0", features = ["max_level_debug", "release_max_level_debug"] }
slog-term = "2.4.1"
slog-scope = "4.0"
slog-async = "2.3"
slog-envlogger = "2.1.0"

failure = { path = "../../common/failure_ext", version = "0.0.1-sol2", package = "solana_libra_failure_ext" }
solana_libra_debug_interface = { path = "../../common/debug_interface", version = "0.0.1-sol2"}
solana_libra_admission_control_proto = { path = "../../admission_control/admission_control_proto", version = "0.0.1-sol2" }

solana_libra_types = { path = "../../types", version = "0.0.1-sol2" }
solana_libra_transaction_builder = { path = "../../language/transaction_builder", version = "0.0.1-sol2" }
solana_libra_crypto = { path = "../../crypto/crypto", version = "0.0.1-sol2" }
solana-libra-generate-keypair = { path = "../../config/generate-keypair", version = "0.0.1-sol2" }

threadpool = "1.7.1"
