[package]
name = "solana_libra_storage_proto"
version = "0.0.0-sol6"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra storage_proto"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = "0.1.28"
grpcio = { version = "0.4.4", default-features = false, features = ["protobuf-codec"] }
proptest = "0.9.2"
proptest-derive = "0.1.0"
protobuf = "2.7"

crypto = { path = "../../crypto/legacy_crypto", package = "solana_libra_crypto", version = "0.0.0-sol6" }
failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol6" }
proto_conv = { path = "../../common/proto_conv", features = ["derive"], package = "solana_libra_proto_conv", version = "0.0.0-sol6" }
types = { path = "../../types", package = "solana_libra_types", version = "0.0.0-sol6" }

[build-dependencies]
build_helpers = { path = "../../common/build_helpers", package = "solana_libra_build_helpers", version = "0.0.0-sol6" }
