[package]
name = "solana-libra-nibble"
version = "0.0.1-sol"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra nibble"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
edition = "2018"

[dependencies]
proptest = "0.9.4"
serde = { version = "1.0.101", features = ["derive"] }
