[package]
name = "solana-libra-secret-service"
version = "0.0.1-sol4"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra secret service"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bytes = "0.4.12"
grpcio = { version = "=0.5.0-alpha.4", default-features = false, features = ["prost-codec"] }
futures = "0.1.28"
prost = "0.5.0"
rand = "0.7.0"
rand_chacha = "0.2.2"
serde = { version = "1.0.96", features = ["derive"] }
structopt = "0.3.2"

solana_libra_config = { path = "../../config", version = "0.0.1-sol4" }
solana_libra_crypto = { path = "../crypto", version = "0.0.1-sol4" }
solana_libra_crypto_derive = { path = "../crypto_derive", version = "0.0.1-sol4" }
solana_libra_debug_interface = { path = "../../common/debug_interface", version = "0.0.1-sol4" }
solana-libra-executable-helpers = { path = "../../common/executable-helpers", version = "0.0.1-sol4" }
failure = { package = "solana_libra_failure_ext", path = "../../common/failure_ext", version = "0.0.1-sol4" }
solana_libra_grpc_helpers = { path = "../../common/grpc_helpers", version = "0.0.1-sol4" }
solana_libra_logger = { path = "../../common/logger", version = "0.0.1-sol4" }

[dev-dependencies]
solana_libra_config = { path = "../../config", version = "0.0.1-sol4", features = ["testing"]}

[build-dependencies]
grpcio-compiler = { version = "0.5.0-alpha.2", default-features = false, features = ["prost-codec"] }
