[package]
name = "solana-libra-config-builder"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra config-builder"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
hex = { version = "0.3.2", default-features = false }
parity-multiaddr = { version = "0.5.0", default-features = false }
rand = "0.6.5"
structopt = "0.3.2"

solana-libra-config = { path = ".." }
solana-libra-crypto = { path = "../../crypto/crypto" }
failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext" }
solana-libra-generate-keypair = { path = "../generate-keypair" }
solana-libra-logger = { path = "../../common/logger" }
solana-libra-prost-ext = { path = "../../common/prost-ext" }
solana-libra-types = { path = "../../types" }
solana_libra_vm_genesis = { path = "../../language/vm/vm_genesis" }

[dev-dependencies]
solana-libra-types = { path = "../../types", features = ["testing"]}
