[package]
name = "solana_libra_invalid_mutations"
version = "0.0.0"
edition = "2018"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra invalid_mutations"
license = "Apache-2.0"

[dependencies]
proptest = "0.9"
proptest_helpers = { path = "../../../common/proptest_helpers", package = "solana_libra_proptest_helpers", version = "0.0.0" }
vm = { path = "../../vm", package = "solana_libra_vm", version = "0.0.0" }
