[package]
name = "solana_libra_jellyfish_merkle"
version = "0.0.1-sol2"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra jellyfish merkle"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bincode = "1.1.1"
byteorder = "1.3.2"
num-derive = "0.2"
num-traits = "0.2"
proptest = "0.9.2"
proptest-derive = "0.1.2"
serde = { version = "1.0.89", features = ["derive"] }

solana_libra_crypto = { path = "../../crypto/crypto", version = "0.0.1-sol2" }
failure = { path = "../../common/failure_ext", version = "0.0.1-sol2", package = "solana_libra_failure_ext" }
solana_libra_nibble = { path = "../../common/nibble", version = "0.0.1-sol2" }
solana_libra_types = { path = "../../types", version = "0.0.1-sol2" }

[dev-dependencies]
rand = "0.6.5"
solana_libra_types = { path = "../../types", version = "0.0.1-sol2", features = ["testing"]}

[features]
default = []
testing = ["solana_libra_types/testing"]
