[package]
name = "solana_libra_jellyfish_merkle"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra jellyfish merkle"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bincode = "1.1.1"
byteorder = "1.3.2"
num-derive = "0.2"
num-traits = "0.2"
proptest = "0.9.2"
proptest-derive = "0.1.2"
serde = { version = "1.0.89", features = ["derive"] }

solana-libra-crypto = { path = "../../crypto/crypto", version = "0.1.0" }
failure = { path = "../../common/failure_ext", version = "0.1.0", package = "solana_libra_failure_ext" }
solana-libra-nibble = { path = "../../common/nibble", version = "0.1.0" }
solana-libra-types = { path = "../../types", version = "0.1.0" }

[dev-dependencies]
rand = "0.6.5"
solana-libra-types = { path = "../../types", version = "0.1.0", features = ["testing"]}

[features]
default = []
testing = ["solana-libra-types/testing"]
