[package]
name = "solana_libra_vm_runtime"
version = "0.0.0-sol6"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra vm_runtime"
license = "Apache-2.0"
edition = "2018"

[dependencies]
rental = "0.5.4"
tiny-keccak = "1.5.0"
proptest = "0.9"
rayon = "1.1"

bytecode_verifier = { path = "../../bytecode_verifier", package = "solana_libra_bytecode_verifier", version = "0.0.0-sol6" }
canonical_serialization = { path = "../../../common/canonical_serialization", package = "solana_libra_canonical_serialization", version = "0.0.0-sol6" }
crypto = { path = "../../../crypto/legacy_crypto", package = "solana_libra_crypto", version = "0.0.0-sol6" }
failure = { path = "../../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol6" }
metrics = { path = "../../../common/metrics", package = "solana_libra_metrics", version = "0.0.0-sol6" }
state_view = { path = "../../../storage/state_view", package = "solana_libra_state_view", version = "0.0.0-sol6" }
types = { path = "../../../types", package = "solana_libra_types", version = "0.0.0-sol6" }
vm = { path = "../", package = "solana_libra_vm", version = "0.0.0-sol6" }
vm_cache_map = { path = "vm_cache_map", package = "solana_libra_vm_cache_map", version = "0.0.0-sol6" }
lazy_static = "1.3.0"
move_ir_natives = { path = "../../stdlib/natives", package = "solana_libra_move_ir_natives", version = "0.0.0-sol6" }
hex = "0.3.2"
config = { path = "../../../config", package = "solana_libra_config", version = "0.0.0-sol6" }
logger = { path = "../../../common/logger", package = "solana_libra_logger", version = "0.0.0-sol6" }

[dependencies.prometheus]
version  = "0.4.2"
default-features = false
features = ["push"]

[dev-dependencies]
assert_matches = "1.3.0"
compiler = { path = "../../compiler", package = "solana_libra_compiler", version = "0.0.0-sol6" }

[features]
instruction_synthesis = []
