[package]
name = "solana_libra_vm_runtime"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra vm runtime"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
hex = "0.3.2"
lazy_static = "1.3.0"
proptest = "0.9"
rayon = "1.1"
rental = "0.5.4"
mirai-annotations = "1.4.0"
prometheus = { version = "0.7.0", default-features = false }

solana_libra_bytecode_verifier = { path = "../../bytecode_verifier", version = "0.1.0" }
solana_libra_canonical_serialization = { path = "../../../common/canonical_serialization", version = "0.1.0" }
solana-libra-config = { path = "../../../config", version = "0.1.0" }
solana-libra-crypto = { path = "../../../crypto/crypto", version = "0.1.0" }
solana-libra-logger = { path = "../../../common/logger", version = "0.1.0" }
solana-libra-metrics = { path = "../../../common/metrics", version = "0.1.0", default-features = false }
solana_libra_state_view = { path = "../../../storage/state_view", version = "0.1.0" }
solana-libra-types = { path = "../../../types", version = "0.1.0" }
solana-libra-vm = { path = "../", version = "0.1.0" }
solana_libra_vm_cache_map = { path = "vm_cache_map", version = "0.1.0" }
solana_libra_vm_runtime_types = { path = "vm_runtime_types", version = "0.1.0" }

[dev-dependencies]
solana-libra-compiler = { path = "../../compiler", version = "0.1.0" }

solana-libra-types = { path = "../../../types", version = "0.1.0", features = ["testing"] }
solana-libra-vm = { path = "../", version = "0.1.0", features = ["testing"]}

[features]
default = []
instruction_synthesis = []
testing = ["solana-libra-types/testing"]
mirai-contracts = []
