[package]
name = "solana_libra_stdlib"
version = "0.0.0"
edition = "2018"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra stdlib"
license = "Apache-2.0"

[dependencies]
bytecode_verifier = { path = "../bytecode_verifier", package = "solana_libra_bytecode_verifier", version = "0.0.0" }
ir_to_bytecode = { path = "../compiler/ir_to_bytecode", package = "solana_libra_ir_to_bytecode", version = "0.0.0" }
types = { path = "../../types", package = "solana_libra_types", version = "0.0.0" }
lazy_static = "1.3.0"
