[package]
name = "solana-libra-stdlib"
version = "0.1.0"
edition = "2018"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra stdlib"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false

[dependencies]
solana_libra_bytecode_verifier = { path = "../bytecode_verifier", version = "0.1.0" }
solana_libra_ir_to_bytecode = { path = "../compiler/ir_to_bytecode", version = "0.1.0" }
solana-libra-types = { path = "../../types", version = "0.1.0" }
lazy_static = "1.3.0"

[dev-dependencies]
solana-libra-types = { path = "../../types", version = "0.1.0", features = ["testing"] }
