[package]
name = "solana_libra_proptest_helpers"
version = "0.0.0"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
crossbeam = "0.7.1"
proptest = "0.9.4"
proptest-derive = "0.1.2"
