[package]
name = "solana_libra_vm_genesis"
version = "0.0.0-sol12"
edition = "2018"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra vm_genesis"
license = "Apache-2.0"

[dependencies]
config = { path = "../../../config", package = "solana_libra_config", version = "0.0.0-sol12" }
crypto = { path = "../../../crypto/legacy_crypto", package = "solana_libra_crypto", version = "0.0.0-sol12" }
failure = { path = "../../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol12" }
ir_to_bytecode = { path = "../../compiler/ir_to_bytecode", package = "solana_libra_ir_to_bytecode", version = "0.0.0-sol12" }
stdlib = { path = "../../stdlib", package = "solana_libra_stdlib", version = "0.0.0-sol12" }
proto_conv = { path = "../../../common/proto_conv", features = ["derive"], package = "solana_libra_proto_conv", version = "0.0.0-sol12" }
state_view = { path = "../../../storage/state_view", package = "solana_libra_state_view", version = "0.0.0-sol12" }
types = { path = "../../../types", package = "solana_libra_types", version = "0.0.0-sol12" }
vm = { path = "../", package = "solana_libra_vm", version = "0.0.0-sol12" }
vm_cache_map = { path = "../vm_runtime/vm_cache_map", package = "solana_libra_vm_cache_map", version = "0.0.0-sol12" }
vm_runtime = { path = "../vm_runtime", package = "solana_libra_vm_runtime", version = "0.0.0-sol12" }
hex = "0.3.2"
lazy_static = "1.3.0"
rand = "0.6.5"
tiny-keccak = "1.5.0"
toml = "0.4"

[dev-dependencies]
canonical_serialization = { path = "../../../common/canonical_serialization", package = "solana_libra_canonical_serialization", version = "0.0.0-sol12" }
proptest = "0.9.3"
proptest-derive = "0.1.1"
proptest_helpers = { path = "../../../common/proptest_helpers", package = "solana_libra_proptest_helpers", version = "0.0.0-sol12" }

[dev-dependencies.types]
features = ["testing"]
path = "../../../types"
version = "0.0.0-sol12"
package = "solana_libra_types"
