[package]
name = "solana_libra_sparse_merkle"
version = "0.0.0-sol11"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra sparse_merkle"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bincode = "1.1.1"
num-derive = "0.2"
num-traits = "0.2"
proptest = "0.9.2"
proptest-derive = "0.1.2"

crypto = { path = "../../crypto/legacy_crypto", package = "solana_libra_crypto", version = "0.0.0-sol11" }
failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol11" }
serde = { version = "1.0.96", features = ["derive"] }
types = { path = "../../types", package = "solana_libra_types", version = "0.0.0-sol11" }

[dev-dependencies]
proptest = "0.9"
rand = "0.6.5"
serde_test = "1.0.96"
