[package]
name = "solana_libra_crypto-derive"
version = "0.0.0-sol6"
description = "Custom derives for `crypto`"
edition = "2018"

[lib]
proc_macro = true

[dependencies]
syn = { version = "0.15.39", features = ["derive"] }
quote = "0.6.13"
