[package]
name = "solana_libra_netcore"
version = "0.0.0-sol5"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bytes = "0.4.12"
futures = { version = "=0.3.0-alpha.17", package = "futures-preview", features = ["io-compat", "compat"] }
futures_01 = { version = "0.1.25", package = "futures" }
pin-utils = "=0.1.0-alpha.4"
tokio = "0.1.22"
yamux = "0.2.1"
parity-multiaddr = "0.4.0"

memsocket = { path = "../memsocket", package = "solana_libra_memsocket", version = "0.0.0-sol5" }
