[package]
name = "solana_libra_move_ir_natives"
version = "0.0.0"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
bitcoin_hashes = "0.3.0"
nextgen_crypto = { path = "../../../crypto/nextgen_crypto", package = "solana_libra_nextgen_crypto", version = "0.0.0" }
failure = { path = "../../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0" }
tiny-keccak = "1.5.0"
types = { path = "../../../types", package = "solana_libra_types", version = "0.0.0" }
byteorder = "1.3.2"
