[package]
name = "solana_libra_memsocket"
version = "0.0.0-sol11"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra memsocket"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
bytes = "0.4.12"
lazy_static = "1.3.0"
futures = { version = "=0.3.0-alpha.17", package = "futures-preview" }
