[package]
name = "solana-libra-storage-service"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = { version = "=0.3.0-alpha.19", package = "futures-preview", features = ["compat"] }
grpcio = { version = "=0.5.0-alpha.4", default-features = false, features = ["prost-codec"] }
structopt = "0.3.2"

solana_libra_canonical_serialization = { path = "../../common/canonical_serialization" }
solana-libra-config = { path = "../../config" }
solana-libra-crypto = { path = "../../crypto/crypto" }
solana_libra_debug_interface = { path = "../../common/debug_interface" }
solana-libra-executable-helpers = { path = "../../common/executable-helpers" }
failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext" }
solana_libra_grpc_helpers = { path = "../../common/grpc_helpers" }
solana-libra-libradb = { path = "../libradb" }
solana-libra-logger = { path = "../../common/logger" }
solana-libra-metrics = { path = "../../common/metrics" }
solana_libra_storage_client = { path = "../storage_client" }
solana_libra_storage_proto = { path = "../storage_proto" }
solana-libra-types = { path = "../../types" }
rand = "0.6.5"

[dev-dependencies]
itertools = "0.8.0"
proptest = "0.9.2"
solana-libra-tools = { path = "../../common/tools" }
solana-libra-libradb = { path = "../libradb", features = ["testing"] }
solana-libra-types = { path = "../../types", features = ["testing"] }

[features]
default = []
testing = ["solana-libra-libradb/testing", "solana-libra-types/testing"]
