[package]
name = "solana-libra-storage-service"
version = "0.0.1-sol2"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra storage service"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = { version = "=0.3.0-alpha.19", package = "futures-preview", features = ["compat"] }
grpcio = { version = "=0.5.0-alpha.4", default-features = false, features = ["prost-codec"] }
structopt = "0.3.2"

solana_libra_canonical_serialization = { path = "../../common/canonical_serialization", version = "0.0.1-sol2" }
solana-libra-config = { path = "../../config", version = "0.0.1-sol2" }
solana-libra-crypto = { path = "../../crypto/crypto", version = "0.0.1-sol2" }
solana_libra_debug_interface = { path = "../../common/debug_interface", version = "0.0.1-sol2" }
solana-libra-executable-helpers = { path = "../../common/executable-helpers", version = "0.0.1-sol2" }
failure = { path = "../../common/failure_ext", version = "0.0.1-sol2", package = "solana_libra_failure_ext" }
solana_libra_grpc_helpers = { path = "../../common/grpc_helpers", version = "0.0.1-sol2" }
solana-libra-libradb = { path = "../libradb", version = "0.0.1-sol2" }
solana-libra-logger = { path = "../../common/logger", version = "0.0.1-sol2" }
solana-libra-metrics = { path = "../../common/metrics", version = "0.0.1-sol2" }
solana_libra_storage_client = { path = "../storage_client", version = "0.0.1-sol2" }
solana_libra_storage_proto = { path = "../storage_proto", version = "0.0.1-sol2" }
solana-libra-types = { path = "../../types", version = "0.0.1-sol2" }
rand = "0.6.5"

[dev-dependencies]
itertools = "0.8.0"
proptest = "0.9.2"
solana-libra-tools = { path = "../../common/tools", version = "0.0.1-sol2" }
solana-libra-libradb = { path = "../libradb", version = "0.0.1-sol2", features = ["testing"] }
solana-libra-types = { path = "../../types", version = "0.0.1-sol2", features = ["testing"] }

[features]
default = []
testing = ["solana-libra-libradb/testing", "solana-libra-types/testing"]
