[package]
name = "solana_libra_proto_conv_derive"
version = "0.0.0-sol14"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra proto_conv_derive"
license = "Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.27"
quote = "0.6.13"
syn = { version = "0.15.39", features = ["full"] }
