[package]
name = "solana_libra_proto_conv_derive"
version = "0.0.0-sol5"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.27"
quote = "0.6.13"
syn = { version = "0.15.39", features = ["full"] }
