[package]
name = "solana_libra_state_view"
version = "0.0.0.4"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0.4" }
types = { path = "../../types", package = "solana_libra_types", version = "0.0.0.4" }
