[package]
name = "solana_libra_state_view"
version = "0.0.0-sol9"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra state_view"
license = "Apache-2.0"
edition = "2018"

[dependencies]
failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol9" }
types = { path = "../../types", package = "solana_libra_types", version = "0.0.0-sol9" }
