[package]
name = "solana_libra_cluster_test"
version = "0.0.0-sol14"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra cluster_test"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol14" }
rand = "0.6.5"
rusoto_core = "0.40.0"
rusoto_kinesis = "0.40.0"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }
serde_json = "1.0"
regex = "1.1.9"
clap = "2.32"
