[package]
name = "solana_libra_network"
version = "0.0.0-sol14"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra network"
license = "Apache-2.0"
build = "build.rs"
publish = false
edition = "2018"

[dependencies]
bytes = "0.4.12"
futures = { version = "=0.3.0-alpha.17", package = "futures-preview", features = ["async-await", "nightly", "io-compat", "compat"] }
lazy_static = "1.3.0"
parity-multiaddr = "0.4.0"
pin-utils = "=0.1.0-alpha.4"
protobuf = { version = "2.7", features = ["with-bytes"] }
rand = "0.6.5"
tokio = "0.1.22"
tokio-timer = "0.2.10"
tokio-retry = "0.2.0"
unsigned-varint = { version = "0.2.2", features = ["codec"] }

channel = { path = "../common/channel", package = "solana_libra_channel", version = "0.0.0-sol14" }
crypto = { path = "../crypto/legacy_crypto", package = "solana_libra_crypto", version = "0.0.0-sol14" }
nextgen_crypto = { path = "../crypto/nextgen_crypto", package = "solana_libra_nextgen_crypto", version = "0.0.0-sol14" }
failure = { path = "../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol14" }
logger = { path = "../common/logger", package = "solana_libra_logger", version = "0.0.0-sol14" }
memsocket = { path = "memsocket", package = "solana_libra_memsocket", version = "0.0.0-sol14" }
metrics = { path = "../common/metrics", package = "solana_libra_metrics", version = "0.0.0-sol14" }
netcore = { path = "netcore", package = "solana_libra_netcore", version = "0.0.0-sol14" }
noise = { path = "noise", package = "solana_libra_noise", version = "0.0.0-sol14" }
socket_bench_server = { path = "socket_bench_server", package = "solana_libra_socket_bench_server", version = "0.0.0-sol14" }
types = { path = "../types", package = "solana_libra_types", version = "0.0.0-sol14" }

[dev-dependencies]
criterion = "0.2.11"

[dev-dependencies.nextgen_crypto]
features = ["testing"]
path = "../crypto/nextgen_crypto"
version = "0.0.0-sol14"
package = "solana_libra_nextgen_crypto"

[build-dependencies]
protoc-rust = { version = "2.5.0", optional = true }

[[bench]]
name = "solana_libra_socket_muxer_bench"
path = "benches/socket_muxer_bench.rs"
harness = false

[[bench]]
name = "solana_libra_network_bench"
path = "benches/network_bench.rs"
harness = false

[features]
default = []
build-proto = ["protoc-rust"]