[package]
name = "solana_libra_debug_interface"
version = "0.0.0-sol10"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra debug_interface"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
grpcio = { version = "0.4.3", default-features = false, features = ["protobuf-codec"] }
futures = "0.1.28"
protobuf = "2.7"

failure = { path = "../failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol10" }
jemalloc = { path = "../jemalloc", package = "solana_libra_jemalloc", version = "0.0.0-sol10" }
logger = { path = "../logger", package = "solana_libra_logger", version = "0.0.0-sol10" }
metrics = { path = "../metrics", package = "solana_libra_metrics", version = "0.0.0-sol10" }

[build-dependencies]
build_helpers = { path = "../build_helpers", package = "solana_libra_build_helpers", version = "0.0.0-sol10", optional = true }

[features]
default = []
build-proto = ["build_helpers"]
