[package]
name = "solana-libra-test-generation"
version = "0.0.1-sol4"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra test generation"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
rand = "0.6.5"
log = "0.4"
env_logger = "0.6"
mirai-annotations = "1.4.0"
structopt = "0.3.2"
solana_libra_bytecode_verifier = { path = "../../bytecode_verifier", version = "0.0.1-sol4" }
solana-libra-cost-synthesis = { path = "../cost-synthesis", version = "0.0.1-sol4" }
solana_libra_vm = { path = "../../vm", version = "0.0.1-sol4" }
solana_libra_vm_runtime = { path = "../../vm/vm_runtime", version = "0.0.1-sol4" }
solana_libra_vm_runtime_types = { path = "../../vm/vm_runtime/vm_runtime_types", version = "0.0.1-sol4" }
solana_libra_vm_cache_map = { path = "../../vm/vm_runtime/vm_cache_map", version = "0.0.1-sol4" }
solana_libra_language_e2e_tests = { path = "../../e2e_tests", version = "0.0.1-sol4" }
solana_libra_stdlib = { path = "../../stdlib", version = "0.0.1-sol4" }
solana_libra_types = { path = "../../../types", version = "0.0.1-sol4", features = ["testing"] }

[features]
mirai-contracts = []
default = ["solana_libra_vm_runtime/instruction_synthesis"]
