[package]
name = "solana_libra_ir_to_bytecode_syntax"
version = "0.0.1-sol3"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra ir to bytecode syntax"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
edition = "2018"
build = "build.rs"

[dependencies]
codespan = "0.2.1"
failure = { path = "../../../../common/failure_ext", version = "0.0.1-sol3", package = "solana_libra_failure_ext" }
hex = "0.3.2"
lazy_static = "1.4.0"
lalrpop-util = "0.17.2"
regex = { version = "1.3.0", default-features = false, features = ["std", "perf"] }
solana_libra_types = { path = "../../../../types", version = "0.0.1-sol3" }

[dev-dependencies]
solana_libra_types = { path = "../../../../types", version = "0.0.1-sol3", features = ["testing"] }

[build-dependencies]
lalrpop = "0.17.2"
