[package]
name = "solana_libra_ir_to_bytecode_syntax"
version = "0.0.0"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"
build = "build.rs"

[dependencies]
codespan = "0.1.3"
codespan-reporting = "0.1.4"
hex = "0.3.2"
lalrpop-util = "0.16.3"
regex = "1.1.9"
types = { path = "../../../../types", package = "solana_libra_types", version = "0.0.0" }

[build-dependencies]
lalrpop = "0.16.3"
