[package]
name = "solana_libra_accumulator"
version = "0.0.0"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
proptest = "0.9.1"

crypto = { path = "../../crypto/legacy_crypto", package = "solana_libra_crypto", version = "0.0.0" }
failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0" }
types = { path = "../../types", package = "solana_libra_types", version = "0.0.0" }

[dev-dependencies]
rand = "0.6.5"
