[package]
name = "solana_libra_schemadb"
version = "0.0.0-sol13"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra schemadb"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
lazy_static = "1.3.0"

failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol13" }
metrics = { path = "../../common/metrics", package = "solana_libra_metrics", version = "0.0.0-sol13" }

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
rev = "8d6cda70f22da2cd15ed7351fcffa9add3444595"

[dev-dependencies]
byteorder = "1.3.2"
tempfile = "3.1.0"
