[package]
name = "solana-libra-bytecode-to-boogie"
version = "0.0.1-sol2"
authors = ["Libra <oncall+libra@xmail.facebook.com>"]
description = "Libra bytecode to boogie"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
solana_libra_bytecode_verifier = { path = "../../bytecode_verifier", version = "0.0.1-sol2" }
solana-libra-vm = { path = "../../vm", version = "0.0.1-sol2" }
solana-libra-types = { path = "../../../types", version = "0.0.1-sol2" }
solana_libra_ir_to_bytecode = { path = "../../compiler/ir_to_bytecode", version = "0.0.1-sol2" }
solana_libra_stackless_bytecode_generator = { path = "../generator", version = "0.0.1-sol2"}
solana-libra-stdlib = { path = "../../stdlib", version = "0.0.1-sol2" }
num = "0.2.0"

[dev-dependencies]
proptest = "0.9"
solana-libra-types = { path = "../../../types", version = "0.0.1-sol2", features = ["testing"]}
