[package]
name = "solana_libra_config"
version = "0.0.0-sol10"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra config"
license = "Apache-2.0"
edition = "2018"

[dependencies]
clap = "2.32"
get_if_addrs = "0.5.3"
hex = "0.3.2"
parity-multiaddr = "0.4.0"
rand = "0.6.5"
serde = { version = "1.0.96", features = ["derive"] }
tempfile = "3.1.0"
toml = "0.4"

crypto = { path = "../crypto/legacy_crypto", package = "solana_libra_crypto", version = "0.0.0-sol10" }
proto_conv = { path = "../common/proto_conv", package = "solana_libra_proto_conv", version = "0.0.0-sol10" }
logger = { path = "../common/logger", package = "solana_libra_logger", version = "0.0.0-sol10" }
failure = { path = "../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol10" }
types = { path = "../types", package = "solana_libra_types", version = "0.0.0-sol10" }
