[package]
name = "solana_libra_generate_keypair"
version = "0.0.0-sol5"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bincode = "1.1.1"
clap = {version = "2.32"}
serde = { version = "1.0.96", features = ["derive"] }
serde_json = "1.0.40"
tempdir = "0.3.7"

crypto = { path = "../../crypto/legacy_crypto", package = "solana_libra_crypto", version = "0.0.0-sol5" }
failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol5" }
