[package]
name = "solana_libra_cost_synthesis"
version = "0.0.0-sol5"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
csv = "1.1.1"
rand = "0.6.5"
lazy_static = "1.3.0"

bytecode_verifier = { path = "../../bytecode_verifier", package = "solana_libra_bytecode_verifier", version = "0.0.0-sol5" }
failure = { path = "../../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol5" }
stdlib = { path = "../../stdlib", package = "solana_libra_stdlib", version = "0.0.0-sol5" }
types = { path = "../../../types", package = "solana_libra_types", version = "0.0.0-sol5" }
vm = { path = "../../vm", package = "solana_libra_vm", version = "0.0.0-sol5" }
vm_runtime = { path = "../../vm/vm_runtime", package = "solana_libra_vm_runtime", version = "0.0.0-sol5" }
language_e2e_tests = { path = "../../e2e_tests", package = "solana_libra_language_e2e_tests", version = "0.0.0-sol5" }
vm_cache_map = { path = "../../vm/vm_runtime/vm_cache_map", package = "solana_libra_vm_cache_map", version = "0.0.0-sol5" }
move_ir_natives = { path = "../../stdlib/natives", package = "solana_libra_move_ir_natives", version = "0.0.0-sol5" }
crypto = { path = "../../../crypto/legacy_crypto", package = "solana_libra_crypto", version = "0.0.0-sol5" }
state_view = { path = "../../../storage/state_view", package = "solana_libra_state_view", version = "0.0.0-sol5" }

[features]
default = ["vm_runtime/instruction_synthesis"]
