[package]
name = "solana_libra_vm_cache_map"
version = "0.0.0-sol11"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra vm_cache_map"
license = "Apache-2.0"
edition = "2018"

[dependencies]
chashmap = "2.2.2"
typed-arena = "1.4.1"

[dev-dependencies]
crossbeam = "0.7"
proptest = "0.9"
rand = "0.6.5"
