[package]
name = "solana_libra_config_builder"
version = "0.0.0-sol14"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra config_builder"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bincode = "1.1.1"
clap = "2.32"
hex = "0.3.2"
serde = { version = "1.0.96", features = ["derive"] }
tempfile = "3.1.0"
toml = "0.4"

config = { path = "..", package = "solana_libra_config", version = "0.0.0-sol14" }
crypto = { path = "../../crypto/legacy_crypto", package = "solana_libra_crypto", version = "0.0.0-sol14" }
nextgen_crypto = { path = "../../crypto/nextgen_crypto", package = "solana_libra_nextgen_crypto", version = "0.0.0-sol14" }
failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol14" }
generate_keypair = { path = "../generate_keypair", package = "solana_libra_generate_keypair", version = "0.0.0-sol14" }
proto_conv = { path = "../../common/proto_conv", features = ["derive"], package = "solana_libra_proto_conv", version = "0.0.0-sol14" }
types = { path = "../../types", package = "solana_libra_types", version = "0.0.0-sol14" }
vm_genesis = { path = "../../language/vm/vm_genesis", package = "solana_libra_vm_genesis", version = "0.0.0-sol14" }
