[package]
name = "solana_libra_stackless_bytecode_generator"
version = "0.0.1-sol"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra stackless bytecode generator"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
solana-libra-vm = { path = "../../vm", version = "0.0.1-sol" }
solana_libra_ir_to_bytecode = { path = "../../compiler/ir_to_bytecode", version = "0.0.1-sol" }
solana-libra-stdlib = { path = "../../stdlib", version = "0.0.1-sol" }
#
[dev-dependencies]
# solana_libra_invalid_mutations = { path = "invalid_mutations" }
proptest = "0.9"
solana-libra-types = { path = "../../../types", version = "0.0.1-sol", features = ["testing"]}
