[package]
name = "solana_libra_repl"
version = "0.0.0-sol5"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bytecode_verifier = { path = "../../bytecode_verifier", package = "solana_libra_bytecode_verifier", version = "0.0.0-sol5" }
compiler = { path = "../../compiler", package = "solana_libra_compiler", version = "0.0.0-sol5" }
failure = { path = "../../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol5" }
getopts = "0.2.18"
language_e2e_tests = { path = "../../e2e_tests", package = "solana_libra_language_e2e_tests", version = "0.0.0-sol5" }
stdlib = { path = "../../stdlib", package = "solana_libra_stdlib", version = "0.0.0-sol5" }
types = { path = "../../../types", package = "solana_libra_types", version = "0.0.0-sol5" }
vm_runtime = { path = "../../vm/vm_runtime", package = "solana_libra_vm_runtime", version = "0.0.0-sol5" }
hex = "0.3.2"
