[package]
name = "solana_libra_bytecode_verifier"
version = "0.0.0-sol13"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra bytecode_verifier"
license = "Apache-2.0"
edition = "2018"

[dependencies]
mirai-annotations = "^1.2.2"
petgraph = "0.4"

failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol13" }
vm = { path = "../vm", package = "solana_libra_vm", version = "0.0.0-sol13" }
types = { path = "../../types", package = "solana_libra_types", version = "0.0.0-sol13" }

[dev-dependencies]
invalid_mutations = { path = "invalid_mutations", package = "solana_libra_invalid_mutations", version = "0.0.0-sol13" }
proptest = "0.9"
