[package]
name = "solana_libra_bytecode_verifier"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra bytecode verifier"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
mirai-annotations = "1.4.0"
petgraph = "0.4"

failure = { path = "../../common/failure_ext", version = "0.1.0", package = "solana_libra_failure_ext" }
solana-libra-vm = { path = "../vm", version = "0.1.0" }
solana-libra-types = { path = "../../types", version = "0.1.0" }
solana_libra_vm_runtime_types = { path = "../vm/vm_runtime/vm_runtime_types", version = "0.1.0" }


[dev-dependencies]
solana_libra_invalid_mutations = { path = "invalid_mutations", version = "0.1.0" }
solana-libra-types = { path = "../../types", version = "0.1.0", features = ["testing"]}
solana-libra-vm = { path = "../vm", version = "0.1.0", features = ["testing"]}

[features]
default = []
testing = ["solana-libra-vm/testing", "solana-libra-types/testing"]
