[package]
name = "solana_libra_failure_macros"
version = "0.0.0-sol11"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra failure_macros"
license = "Apache-2.0"
edition = "2018"

[dependencies]
