[package]
name = "solana_libra_failure_macros"
version = "0.0.1-sol"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra failure macros"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
edition = "2018"

[dependencies]
