[package]
name = "solana_libra_ir_to_bytecode"
version = "0.0.1-sol4"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra ir to bytecode"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
edition = "2018"

[dependencies]
failure = { path = "../../../common/failure_ext", version = "0.0.1-sol4", package = "solana_libra_failure_ext" }
solana_libra_ir_to_bytecode_syntax = { path = "syntax", version = "0.0.1-sol4" }
solana_libra_types = { path = "../../../types", version = "0.0.1-sol4" }
solana_libra_vm = { path = "../../vm", version = "0.0.1-sol4" }
lalrpop-util = "0.17.2"
log = "0.4.7"
codespan = "0.2.1"
codespan-reporting = "0.2.1"

[dev-dependencies]
solana_libra_types = { path = "../../../types", version = "0.0.1-sol4", features = ["testing"] }
