[package]
name = "solana_libra_ir_to_bytecode"
version = "0.0.0"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
failure = { path = "../../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0" }
ir_to_bytecode_syntax = { path = "syntax", package = "solana_libra_ir_to_bytecode_syntax", version = "0.0.0" }
types = { path = "../../../types", package = "solana_libra_types", version = "0.0.0" }
vm = { path = "../../vm", package = "solana_libra_vm", version = "0.0.0" }
lalrpop-util = "0.16.3"
log = "0.4.7"
codespan = "0.1.3"
codespan-reporting = "0.1.4"
regex = "1.1.9"
