[package]
name = "solana_libra_proto_conv"
version = "0.0.0"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
protobuf = "2.7"
failure = { path = "../failure_ext", package = "solana_libra_failure_ext", version = "0.0.0" }
proto_conv_derive = { path = "proto_conv_derive", optional = true, package = "solana_libra_proto_conv_derive", version = "0.0.0" }

[dev-dependencies]
proptest = "0.9.2"
proptest-derive = "0.1.0"
protobuf = "2.7"

[build-dependencies]
build_helpers = { path = "../../common/build_helpers", package = "solana_libra_build_helpers", version = "0.0.0" }

[features]
default = []
derive = ["proto_conv_derive"]
