[package]
name = "solana_libra_storage_service"
version = "0.0.0-sol12"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra storage_service"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = { version = "0.3.0-alpha.13", package = "futures-preview", features = ["compat"] }
grpcio = { version = "0.4.4", default-features = false, features = ["protobuf-codec"] }
protobuf = "2.7"

canonical_serialization = { path = "../../common/canonical_serialization", package = "solana_libra_canonical_serialization", version = "0.0.0-sol12" }
config = { path = "../../config", package = "solana_libra_config", version = "0.0.0-sol12" }
crypto = { path = "../../crypto/legacy_crypto", package = "solana_libra_crypto", version = "0.0.0-sol12" }
debug_interface = { path = "../../common/debug_interface", package = "solana_libra_debug_interface", version = "0.0.0-sol12" }
executable_helpers = { path = "../../common/executable_helpers", package = "solana_libra_executable_helpers", version = "0.0.0-sol12" }
failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0-sol12" }
grpc_helpers = { path = "../../common/grpc_helpers", package = "solana_libra_grpc_helpers", version = "0.0.0-sol12" }
libradb = { path = "../libradb", package = "solana_libradb", version = "0.0.0-sol12" }
logger = { path = "../../common/logger", package = "solana_libra_logger", version = "0.0.0-sol12" }
metrics = { path = "../../common/metrics", package = "solana_libra_metrics", version = "0.0.0-sol12" }
proto_conv = { path = "../../common/proto_conv", features = ["derive"], package = "solana_libra_proto_conv", version = "0.0.0-sol12" }
storage_client = { path = "../storage_client", package = "solana_libra_storage_client", version = "0.0.0-sol12" }
storage_proto = { path = "../storage_proto", package = "solana_libra_storage_proto", version = "0.0.0-sol12" }
types = { path = "../../types", package = "solana_libra_types", version = "0.0.0-sol12" }

[dev-dependencies]
itertools = "0.8.0"
proptest = "0.9.2"
tempfile = "3.1.0"
