[package]
name = "solana_libra_fuzzer"
version = "0.0.0"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra fuzzer"
license = "Apache-2.0"
edition = "2018"

[dependencies]
failure = { path = "../../common/failure_ext", package = "solana_libra_failure_ext", version = "0.0.0" }
byteorder = "1.3.2"
hex = "0.3.2"
lazy_static = "1.3"
proptest = "0.9.3"
sha-1 = "0.8"
structopt = "0.2.15"
proto_conv = { path = "../../common/proto_conv", package = "solana_libra_proto_conv", version = "0.0.0" }
canonical_serialization = { path = "../../common/canonical_serialization", package = "solana_libra_canonical_serialization", version = "0.0.0" }

# List out modules with data structures being fuzzed here.
types = { path = "../../types", package = "solana_libra_types", version = "0.0.0" }
vm = { path = "../../language/vm", package = "solana_libra_vm", version = "0.0.0" }
vm_runtime = { path = "../../language/vm/vm_runtime", package = "solana_libra_vm_runtime", version = "0.0.0" }

[dev-dependencies]
datatest = "0.3.5"
stats_alloc = "0.1.8"
rusty-fork = "0.2.2"
