[package]
name = "solana_libra_serializer_tests"
version = "0.0.1-sol2"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra serializer tests"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dev-dependencies]
proptest = "0.9"
proptest-derive = "0.1.1"
solana_libra_vm = { path = "../", version = "0.0.1-sol2", features = ["testing"]}

[features]
testing = ["solana_libra_vm/testing"]
