[package]
name = "solana_libra_serializer_tests"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dev-dependencies]
proptest = "0.9"
proptest-derive = "0.1.1"
solana-libra-vm = { path = "../", version = "0.1.0", features = ["testing"]}

[features]
testing = ["solana-libra-vm/testing"]
