[package]
name = "solana_libra_noise"
version = "0.0.0-sol12"
authors = ["Solana Maintainers <maintainers@solana.com>", "Libra Association <opensource@libra.org>"]
repository = "https://github.com/solana-labs/libra"
homepage = "https://solana.com/"
description = "Solana Libra noise"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = { version = "=0.3.0-alpha.17", package = "futures-preview" }
snow = { version = "0.5.2", features=["ring-accelerated"]}

crypto = { path = "../../crypto/legacy_crypto", package = "solana_libra_crypto", version = "0.0.0-sol12" }
netcore = { path = "../netcore", package = "solana_libra_netcore", version = "0.0.0-sol12" }
logger = { path = "../../common/logger", package = "solana_libra_logger", version = "0.0.0-sol12" }

[dev-dependencies]
memsocket = { path = "../memsocket", package = "solana_libra_memsocket", version = "0.0.0-sol12" }
