[package]
name = "solana_libra_grpc_helpers"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
grpcio = { version = "0.4.3", default-features = false, features = ["protobuf-codec"] }
futures = { version = "0.3.0-alpha.13", package = "futures-preview", features = ["compat"] }
futures_01 = { version = "0.1.25", package = "futures" }

failure = { path = "../failure_ext", package = "solana_libra_failure_ext" }
logger = { path = "../logger", package = "solana_libra_logger" }
metrics = { path = "../metrics", package = "solana_libra_metrics" }

[dependencies.prometheus]
version  = "0.4.2"
default-features = false
features = ["push"]
